# Generated by Django 5.1.7 on 2025-03-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="eamil",
            new_name="email",
        ),
    ]
